# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dae7f9b5ac9018b7cc6a66a7922afaffa6d1c9f197949a31d4c071c08a005b43849c306b18c2a54b415b9a7e00485fa4292c6efa47b5c387548f601c117bc09

test:
  secret_key_base: 0fe506c3c528be6e78f950ce91bd5b5f00ac46d7352f45d46284343a8603ac7f865a0354ef6e586bfc14d03b01a80dcdd008eac0eea4113ffe6232c5636f1eff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
